### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by samayala22** [DocYard-ai/UCR#2]
```
Traceback (most recent call last):
  File "c:\Users\samay\Documents\Esports_Highlights\tools\temp.py", line 67, in <module>
    result = ocr.predict(c_1_padr,verbose=True,return_type='df',save_tsv=False)
  File "c:\Python\Python39\lib\site-packages\ucr\ucr.py", line 409, in predict
    return super().__call__(
  File "c:\Python\Python39\lib\site-packages\ucr\inference\infer_system.py", line 265, in __call__
    dt_boxes, rec_res = self.perform_ocr(
  File "c:\Python\Python39\lib\site-packages\ucr\inference\infer_system.py", line 110, in perform_ocr
    dt_boxes, elapse = self.text_detector(img)
  File "c:\Python\Python39\lib\site-packages\ucr\inference\infer_det.py", line 138, in __call__
    output_tensors = self.predictor(input_tensors)
  File "c:\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\Python\Python39\lib\site-packages\ucr\core\architecture\base_architecture.py", line 78, in forward
    x = self.neck(x)
  File "c:\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\Python\Python39\lib\site-packages\ucr\core\architecture\neck\craft_fpn.py", line 50, in forward
    y = torch.cat([y, sources[4]], dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 586.00 MiB (GPU 0; 6.00 GiB total capacity; 3.98 GiB already allocated; 55.11 MiB free; 4.02 GiB reserved in total by PyTorch)
```

**Comment by RamanHacks** [comment]
your cuda memory might be already in use. try restarting your jupyter notebook kernel and try it again. If still persists, please share the screenshot of `nvidia-smi`, if using linux system or windows-gpu memory usage using task-manager!

**Comment by samayala22** [comment]
I just realised that this is happening only when the **input is an array**. It works fine with an image although the VRAM usage is still enormous (about 4.5GB)

I'm running the OCR in a local python 3.9 script on Windows 10. Here's the [link](https://prnt.sc/11wdn9v) to the screenshot. 

You can see that my VRAM usage jumps and the script crashes. I tried with Pytorch 1.71 and 1.8.1.

Here's how I'm calling the library:

```python
ocr = UCR(l='en_number')
result = ocr.predict(img,return_type='list',save_tsv=False)
```

`img` is a small numpy array (25x25)

**Comment by RamanHacks** [comment]
@samayala22 the reason for high VRAM usage is because torch allocates some unused memory as cache. Also there was a slip from my side where I din't put the prediction script inside `torch.no_grad()` context manager. I have fixed both the issues in the newest release (0.2.16). Upgrade ucr package using `pip install -U ucr`. 
Also, the prediction doesn't depend on the input image size as all the inputs are scaled to 1920 * _ dimension size. See this config [det_craft.yaml](https://github.com/DocYard-ai/UCR/blob/develop/ucr/conf/preprocess/det_craft.yaml). You can either change the preprocessing step altogether or change the value of `resize_long` parameter by:
`ucr predict 'input_path' --lang "en_number" --det_overrides "Preprocess.0.DetResizeForTest.resize_long=1080"`   
or  
`from ucr import UCR`  
`ocr = UCR(lang="en_number")`  
`result = ocr.predict('input_path', det_overrides=["Preprocess.0.DetResizeForTest.resize_long=1080"])`

**Comment by samayala22** [comment]
Great ! It works perfectly now. 

However, I noticed some periodic VRAM usage spikes when using the CRAFT algorithm with inputs scaled at high resolutions (as you can see [here](https://prnt.sc/11xaybz)). By using a smaller `resize` parameter (in the det_craft.yaml file), it get rids of those spikes. The spikes don't occur with the DB algorithm (with default parameters). I was wondering why ?

Also, when using a smaller `resize` parameter, you get a faster inference using CRAFT but no differences when using DB.

**Comment by RamanHacks** [comment]
@samayala22 use `Preprocess.0.DetResizeForTest.limit_side_len=1080` in case of DB. Look at this config file: [det_db.yaml](https://github.com/DocYard-ai/UCR/blob/develop/ucr/conf/preprocess/det_db.yaml). 

Later I will consolidate these hyperparameters at one place.

**Comment by samayala22** [comment]
@RamanHacks I already tried modifying the det_db.yaml file but it didn't change the inference speed.
